### PR TITLE
Make azureBlobStorage one of the publish options

### PR DESCRIPTION
**Pull request by taras**
## Motivation

I'm in the process of setting up publishing via CI/CD to Azure Blob Storage. I found that `@techdocs/cli` is not aware of `azureBlobStorage`. It gives `error: Unknown publisher type azureBlobStorag` when trying to publish using `npx @techdocs/cli publish --publisher-type azureBlobStorage`.

## Approach

1. Added `azureBlobStorage` as an option. 
2. According to [Configuring Azure Blob Storage Container with TechDocs](https://backstage.io/docs/features/techdocs/using-cloud-storage#configuring-azure-blob-storage-container-with-techdocs), Azure Blob Storage configuration needs `containerName` instead of `bucketName` so I'm using that key. 
3. Added an `--azureAccountName` argument to publish command which allows activating authentication with Azure.
4. Added `--azureAccountKey` argument to provide authorization key for Azure Storage Account.

I did a bit of refactoring to eliminate mutation and check for valid publisher type before executing the rest of the command.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Related https://github.com/backstage/techdocs-cli/issues/27

**Review by OrkoHunter — APPROVED** [review]
Thanks! This still needs a bump of `@backstage/techdocs-common` package for the Azure publish feature to be available.

Another concern is that Azure Publisher needs a `techdocs.publisher.azureBlobStorage.credentials.accountName` account name in the config 
https://backstage.io/docs/features/techdocs/using-cloud-storage#configuring-azure-blob-storage-container-with-techdocs

There are two ways of getting it from the user - 1. via an extra `--azureAccountName` option or 2. Read from a made-up environment variable name like `AZURE_ACCOUNT_NAME` and document it well.

**Comment by taras** [comment]
Would it makes sense to just accept the app-config.yaml file instead of converting arguments into a file that has that format?

**Comment by OrkoHunter** [comment]
> Would it makes sense to just accept a file in app-config.yaml format instead of converting arguments into a file that has that format?

IMHO file based config for techdocs-cli is a bit too much. Asking users to create a file before running a `techdocs-cli` command feels cumberson (either creating the file on the fly or commiting in each repository).

**Comment by taras** [comment]
On the other hand, having to remember different environment variables and different ways of doing configuration for each tool in Backstage ecosystem is going to be a lot of overhead. We're already using the Backstage ConfigReader class internally which has patterns for overloading environment variables with APP_CONFIG prefix. If we're going to expand API surface, it would help if it at least followed some conventions that the person would know from setting up their app. 

Once we agree on the approach, there are optimizations that we can make to make it easier.

**Comment by taras** [comment]
> Asking users to create a file before running a techdocs-cli command feels cumberson (either creating the file on the fly or commiting in each repository).

Yeah, I agree.

**Comment by taras** [comment]
The slightly annoying bit here is that we already do all of this configuration in app-config.yaml. We then rebuild it completely inside techdocs-cli. It would be nice if we could just use the same configuration or just copy and paste it. 🤷

**Comment by taras** [comment]
The answer might just be to add `azureAccountName` argument and punt on any other changes. If we come up with a way to share config then we can deprecate these in the future, if necessary.

**Comment by OrkoHunter** [comment]
Merging this and will make a new release later today!

**Pull request merged**
